- network: 2.2.2.2
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.1.2

- network: 3.3.3.3
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.3.2

- network: 4.4.4.4
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.1.2

- network: 4.4.4.4
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.3.2

- network: 88.88.88.88
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.1.2

- network: 88.88.88.88
  mask: /32
  distance: '110'
  protocol: O
  type: ''
  nexthopip: 10.1.3.2


